### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RasmusVraa** [wsaada19/CommunityQuests#31]
[15:45:10 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'CommunityQuests-2.0.1 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "itemRewards" is null
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:524) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "itemRewards" is null
        at me.wonka01.ServerQuests.configuration.QuestLibrary.getRewardsFromConfig(QuestLibrary.java:88) ~[CommunityQuests-2.0.1 (1).jar:?]
        at me.wonka01.ServerQuests.configuration.QuestLibrary.loadQuestFromConfig(QuestLibrary.java:52) ~[CommunityQuests-2.0.1 (1).jar:?]
        at me.wonka01.ServerQuests.configuration.QuestLibrary.loadQuestConfiguration(QuestLibrary.java:32) ~[CommunityQuests-2.0.1 (1).jar:?]
        at me.knighthat.apis.files.Config.initializeQuests(Config.java:38) ~[CommunityQuests-2.0.1 (1).jar:?]
        at me.knighthat.apis.files.Config.<init>(Config.java:22) ~[CommunityQuests-2.0.1 (1).jar:?]
        at me.wonka01.ServerQuests.ServerQuests.<init>(ServerQuests.java:24) ~[CommunityQuests-2.0.1 (1).jar:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
        at java.lang.Class.newInstance(Class.java:725) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.1.jar:git-Purpur-2062]
        ... 9 more

**Comment by wsaada19** [comment]
Fixed in latest release
